language: node_js

node_js:
  - 8.1.4

before_script:
  - webpack -d
  - npm install grunt-cli -g
  - grunt pgcreatedb:default
  - knex migrate:latest --env NODE_ENV
  - knex seed:run --env NODE_ENV

cache: yarn

script:
  - yarn test

services:
  - postgresql

env:
  - NODE_ENV=test