language: node_js

node_js:
  - 8.1.4

before_script:
  - webpack -d
  - npm install grunt-cli -g
  - psql -c 'create database thesis_test;' -U postgres

script:
  - yarn test

services:
  - postgresql

env:
  - NODE_ENV=test