version: '3'

services:
  tripvalet:
    build: .
    depends_on:
      - 'redis'
      - 'postgresdb'
    ports: 
      - '3000:3000'
    links:
      - postgresdb

  redis:
    image: 'redis:alpine'
    volumes: 
      - 'data-volume:/var/lib/redis/data'

  postgresdb:
    image: 'postgres:9.6-alpine'
    volumes:
      - 'data-volume:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: tripvalet_devel

volumes:
  data-volume: